{% set name = "aws-embedded-metrics" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 690fa7b56e1320c8189b80d0ec07719e73137c0471037c574a65d99898c63988

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.14
    - pip
    - setuptools
  run:
    - python >=3.6,<3.14
    - aiohttp

test:
  imports:
    - aws_embedded_metrics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awslabs/aws-embedded-metrics-python
  summary: AWS Embedded Metrics Package
  license: Apache-2.0 AND BSD-3-Clause
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - zuoyuan-alt
    - seoberha
    - zuoyuanh
